# Generated by Django 5.1.1 on 2024-10-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
